import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next'; import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api/client'; import { MemorialDesign } from '../components/MemorialDesign'; import type { Memorial } from '../types';
export function MemorialDetailPage() {
  const { id } = useParams(); const { t } = useTranslation(); const navigate = useNavigate(); const [item, setItem] = useState<Memorial>(); const [editing, setEditing] = useState(false);
  const load = () => api.get('/admin/memorials').then((r) => setItem(r.data.find((x: Memorial) => x._id === id)));
  useEffect(() => { void load(); }, [id]);
  if (!item) return <p>{t('loading')}</p>;
  const act = async (action: 'approve'|'reject') => { await api.put(`/admin/memorials/${id}/${action}`); navigate('/admin/memorials'); };
  const save = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const fd = new FormData(e.currentTarget); await api.put(`/admin/memorials/${id}`, Object.fromEntries(fd.entries())); setEditing(false); await load(); };
  return <><Link className="back-link" to="/admin/memorials">← {t('back')}</Link><div className="review-grid"><MemorialDesign memorial={item} compact /><section className="review-panel"><div className="row"><div><p className="eyebrow">{t('review')}</p><h1>{item.fullName}</h1></div><span className={`status ${item.status}`}>{t(item.status)}</span></div>{editing ? <form className="edit-form" onSubmit={save}>{['fullName','birthDate','deathDate','relationship','religion','message'].map((field) => <label key={field}>{field}<input name={field} type={field.includes('Date') ? 'date' : 'text'} defaultValue={field.includes('Date') ? item[field as 'birthDate'].slice(0,10) : String(item[field as keyof Memorial])} /></label>)}<button className="button primary">{t('save')}</button></form> : <><dl className="detail-list"><div><dt>{t('relationship')}</dt><dd>{item.relationship}</dd></div><div><dt>Religion / type</dt><dd>{item.religion}</dd></div><div><dt>{t('reminder')}</dt><dd>{item.reminderEnabled ? t('yes') : t('no')}</dd></div><div><dt>Template</dt><dd>{item.template}</dd></div></dl><p className="message-text">“{item.message}”</p></>}<div className="action-row"><button className="button" onClick={() => setEditing(!editing)}>{t('edit')}</button><button className="button danger" onClick={() => void act('reject')}>{t('reject')}</button><button className="button primary" onClick={() => void act('approve')}>{t('approve')}</button></div></section></div></>;
}
