const router = require('express').Router();
const auth = require('../controllers/authController');
const { protect } = require('../middleware/auth');
router.post('/register', auth.register);
router.post('/login', auth.login);
router.post('/refresh', auth.refresh);
router.get('/me', protect, auth.me);
router.patch('/me', protect, auth.updateProfile);
router.post('/logout', protect, auth.logout);
module.exports = router;
